"""schema inicial

Revision ID: 60773207356d
Revises: 
Create Date: 2026-08-18 09:42:48.949276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '60773207356d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_execucoes_motor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_execucao', sa.Date(), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estruturas_processadas', sa.Integer(), nullable=False),
    sa.Column('eventos_gerados', sa.Integer(), nullable=False),
    sa.Column('erros', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_execucoes_motor_data_execucao'), 'log_execucoes_motor', ['data_execucao'], unique=False)
    op.create_table('precos_mercado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('preco', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('fonte', sa.String(length=30), nullable=False),
    sa.Column('hora_captura', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'data', name='uq_preco_ticker_data')
    )
    op.create_index(op.f('ix_precos_mercado_data'), 'precos_mercado', ['data'], unique=False)
    op.create_index(op.f('ix_precos_mercado_ticker'), 'precos_mercado', ['ticker'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('papel', sa.Enum('sales_trader', 'gestor', 'compliance', 'admin', name='papel'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tabela', sa.String(length=100), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('campo', sa.String(length=100), nullable=False),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_novo', sa.Text(), nullable=True),
    sa.Column('acao', sa.Enum('insert', 'update', 'delete', name='acao_auditoria'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_registro_id'), 'audit_log', ['registro_id'], unique=False)
    op.create_index(op.f('ix_audit_log_tabela'), 'audit_log', ['tabela'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_orbit', sa.String(length=100), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('suitability', sa.String(length=50), nullable=True),
    sa.Column('sales_trader_responsavel_id', sa.Integer(), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('atualizado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['sales_trader_responsavel_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_codigo_orbit'), 'clientes', ['codigo_orbit'], unique=True)
    op.create_table('importacoes_orbit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arquivo', sa.String(length=300), nullable=False),
    sa.Column('linhas_processadas', sa.Integer(), nullable=False),
    sa.Column('novas', sa.Integer(), nullable=False),
    sa.Column('atualizadas', sa.Integer(), nullable=False),
    sa.Column('encerradas', sa.Integer(), nullable=False),
    sa.Column('erros', sa.JSON(), nullable=False),
    sa.Column('importado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['importado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estruturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('operacao_ref', sa.String(length=100), nullable=False),
    sa.Column('tipo_estrutura', sa.String(length=100), nullable=False),
    sa.Column('ativo_principal', sa.String(length=50), nullable=False),
    sa.Column('notional', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('moeda', sa.String(length=10), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('valor_entrada', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('status', sa.Enum('ativa', 'encerrada', 'cancelada', name='status_estrutura'), nullable=False),
    sa.Column('parametros_especificos', sa.JSON(), nullable=False),
    sa.Column('fonte_importacao', sa.String(length=20), nullable=False),
    sa.Column('data_importacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('atualizado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operacao_ref', name='uq_estrutura_operacao_ref')
    )
    op.create_index(op.f('ix_estruturas_data_vencimento'), 'estruturas', ['data_vencimento'], unique=False)
    op.create_index(op.f('ix_estruturas_operacao_ref'), 'estruturas', ['operacao_ref'], unique=False)
    op.create_index(op.f('ix_estruturas_status'), 'estruturas', ['status'], unique=False)
    op.create_index(op.f('ix_estruturas_tipo_estrutura'), 'estruturas', ['tipo_estrutura'], unique=False)
    op.create_table('barreiras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estrutura_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('nivel', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('direcao', sa.String(length=10), nullable=False),
    sa.Column('regra_observacao', sa.String(length=30), nullable=False),
    sa.Column('ativo_referencia', sa.String(length=50), nullable=False),
    sa.Column('status_atual', sa.Enum('normal', 'proxima', 'atingida', name='status_barreira'), nullable=False),
    sa.Column('status_anterior', sa.Enum('normal', 'proxima', 'atingida', name='status_barreira'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['estrutura_id'], ['estruturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barreiras_estrutura_id'), 'barreiras', ['estrutura_id'], unique=False)
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estrutura_id', sa.Integer(), nullable=False),
    sa.Column('tipo_evento', sa.String(length=50), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('preco_referencia', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('fonte', sa.String(length=30), nullable=False),
    sa.Column('regra_utilizada', sa.String(length=200), nullable=False),
    sa.Column('status_anterior', sa.String(length=50), nullable=True),
    sa.Column('status_novo', sa.String(length=50), nullable=True),
    sa.Column('detalhes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['estrutura_id'], ['estruturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_estrutura_id'), 'eventos', ['estrutura_id'], unique=False)
    op.create_index(op.f('ix_eventos_tipo_evento'), 'eventos', ['tipo_evento'], unique=False)
    op.create_table('fixings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estrutura_id', sa.Integer(), nullable=False),
    sa.Column('data_fixing', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('regra', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'observado', 'nao_aplica', name='status_fixing'), nullable=False),
    sa.Column('resultado_observado', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['estrutura_id'], ['estruturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixings_data_fixing'), 'fixings', ['data_fixing'], unique=False)
    op.create_index(op.f('ix_fixings_estrutura_id'), 'fixings', ['estrutura_id'], unique=False)
    op.create_table('panoramas_mensais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('estrutura_id', sa.Integer(), nullable=False),
    sa.Column('competencia', sa.String(length=7), nullable=False),
    sa.Column('conteudo_gerado', sa.Text(), nullable=False),
    sa.Column('conteudo_final', sa.Text(), nullable=True),
    sa.Column('status_aprovacao', sa.Enum('rascunho', 'aprovado', 'rejeitado', name='status_aprovacao_panorama'), nullable=False),
    sa.Column('aprovado_por_id', sa.Integer(), nullable=True),
    sa.Column('aprovado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aprovado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['estrutura_id'], ['estruturas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estrutura_id', 'competencia', name='uq_panorama_estrutura_competencia')
    )
    op.create_index(op.f('ix_panoramas_mensais_cliente_id'), 'panoramas_mensais', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_panoramas_mensais_estrutura_id'), 'panoramas_mensais', ['estrutura_id'], unique=False)
    op.create_index(op.f('ix_panoramas_mensais_status_aprovacao'), 'panoramas_mensais', ['status_aprovacao'], unique=False)
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estrutura_id', sa.Integer(), nullable=True),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('severidade', sa.Enum('info', 'atencao', 'critico', name='severidade_alerta'), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('chave_dedupe', sa.String(length=300), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lido_por_id', sa.Integer(), nullable=True),
    sa.Column('lido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolvido', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['estrutura_id'], ['estruturas.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['lido_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_chave_dedupe'), 'alertas', ['chave_dedupe'], unique=False)
    op.create_index(op.f('ix_alertas_estrutura_id'), 'alertas', ['estrutura_id'], unique=False)
    op.create_index(op.f('ix_alertas_tipo'), 'alertas', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alertas_tipo'), table_name='alertas')
    op.drop_index(op.f('ix_alertas_estrutura_id'), table_name='alertas')
    op.drop_index(op.f('ix_alertas_chave_dedupe'), table_name='alertas')
    op.drop_table('alertas')
    op.drop_index(op.f('ix_panoramas_mensais_status_aprovacao'), table_name='panoramas_mensais')
    op.drop_index(op.f('ix_panoramas_mensais_estrutura_id'), table_name='panoramas_mensais')
    op.drop_index(op.f('ix_panoramas_mensais_cliente_id'), table_name='panoramas_mensais')
    op.drop_table('panoramas_mensais')
    op.drop_index(op.f('ix_fixings_estrutura_id'), table_name='fixings')
    op.drop_index(op.f('ix_fixings_data_fixing'), table_name='fixings')
    op.drop_table('fixings')
    op.drop_index(op.f('ix_eventos_tipo_evento'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_estrutura_id'), table_name='eventos')
    op.drop_table('eventos')
    op.drop_index(op.f('ix_barreiras_estrutura_id'), table_name='barreiras')
    op.drop_table('barreiras')
    op.drop_index(op.f('ix_estruturas_tipo_estrutura'), table_name='estruturas')
    op.drop_index(op.f('ix_estruturas_status'), table_name='estruturas')
    op.drop_index(op.f('ix_estruturas_operacao_ref'), table_name='estruturas')
    op.drop_index(op.f('ix_estruturas_data_vencimento'), table_name='estruturas')
    op.drop_table('estruturas')
    op.drop_table('importacoes_orbit')
    op.drop_index(op.f('ix_clientes_codigo_orbit'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_audit_log_tabela'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_registro_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_precos_mercado_ticker'), table_name='precos_mercado')
    op.drop_index(op.f('ix_precos_mercado_data'), table_name='precos_mercado')
    op.drop_table('precos_mercado')
    op.drop_index(op.f('ix_log_execucoes_motor_data_execucao'), table_name='log_execucoes_motor')
    op.drop_table('log_execucoes_motor')
    # ### end Alembic commands ###
